<a href="https://colab.research.google.com/github/azizbekb/NumPy/blob/main/amaliyot_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 2-o'lchamli massiv yaratish 

**Masala sharti :** Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv yaratuvchi funksiyani davom ettiring.  

**Yordam :**  `arange`dan foydalanish ishni osonlashtiradi 


In [2]:
# JAVOBNI SHU YERGA YOZING
def nd_array():
  """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), 
  qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
  arr=np.arange(9).reshape(3,3)
  return arr
print(nd_array())

[[0 1 2]
 [3 4 5]
 [6 7 8]]


###  Masala(2): Indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish 
**Masala :** Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasini davom ettiring.

**Yordam :** 6 va 7 turgan indekslarni aniqlab olib, shu indekslar yordamida kesib oling. **Natija:** array([6, 7]) ko'rinishida bo'lishi kerak. 

In [3]:
# JAVOBNI SHU YERGA YOZING
def sliced_array_2d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan
     qismini kesib olish funksiyasi """
    array = nd_array() # yuqoridagi funksiya yordamida array yaratib olish
    sliced_array=array[2,:2]
    return sliced_array
print(sliced_array_2d())


[6 7]


###  Masala(3): Indeks yordamida 3-o'lchamli massivdan elementlarni kesib olish 

**Masala :**  3-o'lchamli massivni quyidagi listdan yarating, hamda 12, 13, 15, va 16  elementlarini kesib oluvchi funksiyani davom ettiring.

In [4]:
# JAVOBNI SHU YERGA YOZING
def sliced_array_3d():
    """3-o'lchamli massivni yuqoridagi listdan yaratish, 
    hamda 12, 13, 15, va 16 elementlarini kesib olish funksiyasi"""
    arr=np.arange(27).reshape(3,3,3)
    sliced_array_2d=arr[1, 1:3, :2]
    return sliced_array_2d
print(sliced_array_3d())

[[12 13]
 [15 16]]


###  Masala(4): Boolean indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish 

**Masala :** Bizlarda,  
        
        ['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor']

**list**dagi kishilar va ularning **ma'lumot**lari 
       
      [[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]]
ko'rinishda keltirilgan. 


Mana shu ma'lumotlardan **Javohir** va **Elyor** ismlariga tegishli ma'lumotlarni Boolean indekslash yordamida kesib olish funksiyasini davom ettiring. 
**Yordam :** Boolean indekslash video darsligiga murojat qiling. 
**Natija:** Natija (4, 4) o'lchamli massiv ko'rinishida, hamda dastlabki ikkita qattori quyidagicha

    array([[7, 7, 4, 2],
           [1, 5, 1, 9],
           ...
           ...        ]])

In [5]:
# JAVOBNI SHU YERGA YOZING
def boolean_slicing():
    """Boolean indekslash yordamida ma'lumotlarni kesib olish """
    names=np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
    data=np.array( [[5, 6, 1, 1],
                    [9, 1, 1, 1],
                    [7, 7, 4, 2],
                    [1, 5, 1, 9],
                    [9, 9, 4, 5],
                    [7, 5, 9, 6],
                    [5, 3, 7, 4]])
    mask=(names=='Javohir') | (names=='Elyor')
    
    return data[mask]
print(boolean_slicing())

[[7 7 4 2]
 [1 5 1 9]
 [7 5 9 6]
 [5 3 7 4]]
