<a href="https://colab.research.google.com/github/azizbekb/NumPy/blob/main/amaliyot_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 1-o'lchamli massivlar yaratish
**Masala sharti :** Elementlari ixtiyoriy  *n* ta  (*n* > 0, butun son) bo'lgan 1-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring. 

**Yordam :**  `array` yoki `random` funksiyasidan foydalaning. 






In [ ]:
def one_dim(n):
  """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
  arr=np.random.randn(n)
  return arr
print(one_dim(5))

[-0.44961093 -0.40514261 -0.57490672 -0.11023652 -0.86721151]


### Masala(2) 2-o'lchamli massivlar yaratish 

**Masala :** Shakli `shape(r, c)` bo'lgan 2-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.  

**Yordam :** numpy kutubxonasida massivlar yaratuvchi funksiyalarining istalganidan foydlanishingiz mumkin. 


In [ ]:
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv """
    arr=np.random.randint(5, size=(r,c))
    return arr
print(two_dim(2,4))

[[1 2 2 0]
 [1 0 4 1]]
