<a href="https://colab.research.google.com/github/azizbekb/NumPy/blob/main/amaliyot_yakuniy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini 
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [11]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring! 

`💡Ishora` numpy.array

In [12]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [13]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [14]:
arr=np.arange(10)
xotira_hajmi=arr.size*arr
xotira_hajmi


array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin? 


`💡Ishora` np.info

In [15]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`. See the warnings section below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
    between t

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [16]:
arr=np.zeros(12)
arr[5]=1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [17]:
np.arange(20,60)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring 
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [18]:
vec=np.arange(6)
vec=vec[::-1]
vec

array([5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [19]:
arr=np.arange(12,21).reshape(3,3)
arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0] 





`💡Ishora` np.nonzero

In [20]:
x=np.array([3, 7, 0, 0, 9, 0])
np.nonzero(x)


(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [21]:
arr=np.random.random((2,2,2))
arr

array([[[0.79929818, 0.62529679],
        [0.08143897, 0.21574071]],

       [[0.14627894, 0.58867543],
        [0.85923225, 0.47398841]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [22]:
x=np.random.random((9,9))
print(x.min())
print(x.max())


0.012726272320716547
0.9975967773825795


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [23]:
#nan
False
False
#nan
True
False


False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [24]:
x=np.ones((6,3))
y=np.ones((3,4))
np.dot(x,y)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
#9
#10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

In [26]:
a=np.array([1,2])
b=np.array([4,5])
r1=np.greater(a,b)
r2=np.greater_equal(a,b)
r3=np.less(a,b)
r4=np.less_equal(a,b)
print(r1)
print(r2)
print(r3)
print(r4)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
#nan
#nan
#ValueError: Cannot convert float NaN to integer

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


[link text](https://)`💡Ishora` np.intersect1d

In [28]:
x=np.array([1,2,3,4,5])
y=np.array([2,5,8,9,10])
z=np.intersect1d(x,y)
print(z)


[2 5]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [29]:
arr = np.array([-2.5, 3.7, 4.2, -1.8, 0, -4.1, 2.3, -6.9, 7.1])
positive_integers = arr[arr > 0].astype(int)
print(positive_integers)
positive_integers = np.floor(arr[arr > 0]).astype(int)
print(positive_integers)
positive_integers = (arr[arr > 0]).astype(int)
print(positive_integers)
positive_integers = np.trunc(arr[arr > 0]).astype(int)
print(positive_integers)

[3 4 2 7]
[3 4 2 7]
[3 4 2 7]
[3 4 2 7]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [30]:
x=np.arange(9).reshape(3,3)
x=x%3
x


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [31]:
vec = np.random.randint(0, 100, size=10)
vec.sort()
vec

array([14, 24, 53, 65, 66, 68, 69, 75, 79, 87])

#### 22. A va B nomi bilan ikkita tasodifiy qiymatlardan iborat bo'lgan massiv yarating, so'ng ulardan qaysi biri katta yoki kichik ekanligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [32]:
A = np.random.randint(0, 100, size=10)
B = np.random.randint(0, 100, size=10)
print(A)
print(B)
if np.allclose(A, B) or np.array_equal(A, B):
    print("A va B massivlarining elementlari bir xil")
else:
    result = np.all(A <= B)
    if result:
        print("A massivi B massividan kichik yoki teng")
    else:
        print("A massivi B massividan katta")


[22 18 27 15 89 24 86  3 15 14]
[56 54 20 32 39 13  2 98 14  7]
A massivi B massividan katta


`💡Ishora` np.dot or np.ones

#### 23. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [33]:
a=np.random.rand(5)
print("Asl qiymatlar: ", a)
max_value_index = np.argmax(a)
a[max_value_index] = 0
print("Yangi qiymatlar: ", a)

Asl qiymatlar:  [0.29527323 0.31917038 0.82279432 0.71726573 0.11826031]
Yangi qiymatlar:  [0.29527323 0.31917038 0.         0.71726573 0.11826031]


#### 24. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [34]:
# Bugungi sana
today = np.datetime64('today', 'D')
print("Bugun: ", today)

# Ertangi sana
tomorrow = today + np.timedelta64(1, 'D')
print("Ertaga: ", tomorrow)

# Kecharoq sana
yesterday = today - np.timedelta64(1, 'D')
print("Kecha: ", yesterday)

Bugun:  2023-04-21
Ertaga:  2023-04-22
Kecha:  2023-04-20


#### 25. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [35]:
# 2016 yil yanvar oyining birinchi kuniga mos keladigan sana
start_date = np.datetime64('2016-01-01')

# 2016 yil yanvar oyining oxirgi kuniga mos keladigan sana
end_date = np.datetime64('2016-01-31')

# start_date va end_date orasidagi barcha sanalarni olish uchun np.arange() funksiyasidan foydalanamiz
all_dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')

# Natijani ekranga chiqaramiz
print(all_dates)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 26. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [36]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

result = np.add.reduce([arr1, arr2, arr3])

print(result)

[12 15 18]


#### 27. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [37]:
arr = np.array([1, 2, 3, 4, 5])

# 3 ta nol qo'shamiz
arr_new = np.zeros(len(arr)*4, dtype=int)
arr_new[::4] = arr

print(arr_new)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 28. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 


`💡Ishora` stride_tricks.as_strided

In [38]:
from numpy.lib.stride_tricks import as_strided
a = np.arange(1, 15)
b = as_strided(a, shape=(11, 4), strides=(4, 4))
print(b)

[[          1  8589934592           2 12884901888]
 [ 8589934592           2 12884901888           3]
 [          2 12884901888           3 17179869184]
 [12884901888           3 17179869184           4]
 [          3 17179869184           4 21474836480]
 [17179869184           4 21474836480           5]
 [          4 21474836480           5 25769803776]
 [21474836480           5 25769803776           6]
 [          5 25769803776           6 30064771072]
 [25769803776           6 30064771072           7]
 [          6 30064771072           7 34359738368]]


#### 29. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [39]:
arr = np.array([2, 3, 5, 2, 7, 5, 7, 8, 8, 8, 5, 3, 1, 1, 5])
count = np.bincount(arr)
duplicates = np.where(count > 1)[0]
print(duplicates)

[1 2 3 5 7 8]


#### 30. np.random.rand() va np.random.randn() farqi nimada?

In [40]:
#np.random.rand()-musbat 0 va 1 oralig'idagi sonlardan iborat matrix yaratib beradi

#np.random.randn()-musbat va manfiy -1 va 1 oralig'idagi sonlardan iborat matrix yaratib beradi