<a href="https://colab.research.google.com/github/azizbekb/NumPy/blob/main/amaliyot_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 1-o'lchamli massivlar yaratish
**Masala sharti :** Elementlari ixtiyoriy  *n* ta  (*n* > 0, butun son) bo'lgan 1-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring. 

**Yordam :**  `array` yoki `random` funksiyasidan foydalaning. 






In [3]:
# JAVOBNI SHU YERGA YOZING
def one_dim(n):
  """ n ta elementdan tashkil topgan 1-o'lchamli massiv """
  arr=np.random.randn(n)
  return arr
print(one_dim(5))

[-0.3622854  -1.19224027  1.07572726  0.04328409 -0.01532729]


### Masala(2) 2-o'lchamli massivlar yaratish 

**Masala :** Shakli `shape(r, c)` bo'lgan 2-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.  

**Yordam :** numpy kutubxonasida massivlar yaratuvchi funksiyalarining istalganidan foydlanishingiz mumkin. 


In [4]:
# JAVOBNI SHU YERGA YOZING
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv """
    arr=np.random.randint(5, size=(r,c))
    return arr
print(two_dim(2,4))

[[4 4 1 4]
 [4 3 1 0]]
